// Builds Train objects from the real 2026 WSR timetable data
// (generated by route_data/timetable_2026/build_app_data.py)

import type { Train, TrainStop, StationCode } from '../types/models';
import timetableData from '../data/timetable2026.json';
import { mockStations } from './mockTrainData';
import type { TimetableType, RawService } from './calendarConfig';
import {
  getDayInfo,
  getRepresentativePattern,
  timetableColors,
  timetableNames,
  timetableSummaries
} from './calendarConfig';

function midnightOf(date: Date): Date {
  const d = new Date(date);
  d.setHours(0, 0, 0, 0);
  return d;
}

function buildStop(
  code: StationCode,
  arrival: string | null,
  departure: string | null,
  platform: string | undefined
): TrainStop {
  const station = mockStations.find(s => s.code === code);
  return {
    stationCode: code,
    stationName: station?.name ?? code,
    scheduledArrival: arrival ?? undefined,
    scheduledDeparture: departure ?? undefined,
    actualArrival: undefined,
    actualDeparture: undefined,
    platform,
    isRequestStop: station?.isRequestStop ?? false,
    stopType: !arrival ? 'Origin' : !departure ? 'Destination' : 'Stop',
    status: 'Scheduled',
    delayMinutes: 0
  };
}

function buildTrain(
  service: RawService,
  patternId: string,
  patternTitle: string,
  date: Date,
  index: number
): Train {
  const stops = service.stops.map((s, i) =>
    buildStop(
      s.c as StationCode,
      i === 0 ? null : s.a,
      i === service.stops.length - 1 ? null : (s.d ?? s.a),
      s.p
    )
  );

  const origin = stops[0].stationCode;
  const destination = stops[stops.length - 1].stationCode;
  const departure = (stops[0].scheduledDeparture ?? '0000').replace(':', '');
  const id = `${service.direction}${index + 1}_${departure}`;

  const notes: string[] = [];
  if (service.loco) notes.push(`Hauled by ${service.loco}`);
  if (patternTitle.includes('@') || patternTitle.toLowerCase().includes('event')) {
    notes.push(patternTitle);
  }

  return {
    id,
    serviceId: `${patternId}_${service.direction}_${departure}_${origin}_${destination}`,
    scheduledDate: midnightOf(date),
    origin,
    destination,
    serviceType: service.serviceType,
    operator: 'West Somerset Railway',
    notes: notes.length > 0 ? notes.join(' • ') : undefined,
    status: {
      state: 'Scheduled',
      delayMinutes: 0,
      lastUpdated: new Date()
    },
    stops
  };
}

function buildTrainsFromPattern(
  patternId: string,
  services: RawService[],
  title: string,
  date: Date
): Train[] {
  return services.map((service, index) =>
    buildTrain(service, patternId, title, date, index)
  );
}

// All trains scheduled for a specific date, from the real WSR timetable
export function getTrainsForDate(date: Date): Train[] {
  const info = getDayInfo(date);
  if (info.kind !== 'service' || !info.patternId) {
    return [];
  }
  const pattern = (timetableData.patterns as unknown as Record<string, { services: RawService[] }>)[info.patternId];
  if (!pattern) return [];
  return buildTrainsFromPattern(
    info.patternId,
    pattern.services,
    info.patternTitle ?? '',
    date
  );
}

// Representative trains for a timetable family (used for schedule previews)
export function getTrainsForTimetable(timetableType: TimetableType): Train[] {
  const rep = getRepresentativePattern(timetableType);
  if (!rep) return [];
  return buildTrainsFromPattern(
    rep.id,
    rep.pattern.services,
    rep.pattern.title,
    new Date()
  );
}

export interface FamilySchedule {
  type: TimetableType;
  name: string;
  summary: string;
  color: string;
  trains: Train[];
  activeDays: string;
}

const FAMILY_ACTIVE_DAYS: Partial<Record<TimetableType, string>> = {
  red: 'High season and holiday periods',
  blue: 'Standard running days',
  orange: 'Peak summer days with DMU',
  yellow: 'Quieter running days',
  brown: 'Off-peak running days',
  purple: 'Special event days',
  green: 'Festive period (pre-booked events)'
};

// Schedule cards for every timetable family, driven by the real data
export function getFamilySchedules(): FamilySchedule[] {
  const families: TimetableType[] = ['red', 'blue', 'orange', 'yellow', 'brown', 'purple', 'green'];
  return families.map(type => ({
    type,
    name: timetableNames[type],
    summary: timetableSummaries[type],
    color: timetableColors[type],
    trains: type === 'green' ? [] : getTrainsForTimetable(type),
    activeDays: FAMILY_ACTIVE_DAYS[type] ?? ''
  }));
}
