name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          
      - name: Remove PR preview directory
        run: |
          if [ -d "pr/${{ github.event.number }}" ]; then
            rm -rf pr/${{ github.event.number }}
            echo "Removed preview for PR #${{ github.event.number }}"
          else
            echo "No preview found for PR #${{ github.event.number }}"
          fi
          
      - name: Commit and push cleanup
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Remove preview for PR #${{ github.event.number }}"
            git push
            echo "Cleanup committed"
          else
            echo "No changes to commit"
          fi