name: Deploy Main

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: app/wsr-railway-app/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        working-directory: app/wsr-railway-app
        
      - name: Build
        run: npm run build
        working-directory: app/wsr-railway-app
        env:
          BASE_PATH: /west_somerset_railway/
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: app/wsr-railway-app/dist
          keep_files: false